alias nssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias nscp='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias nsftp='sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias ngit='GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git'
alias ntmux-synchronize-ssh='tmux-synchronize-ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
